r"""
Barnsley fern, Sierpinski triangle, and Sierpinski carpet
===============================================================

Three classic iterated-function-system fractals, all generated by the
same "chaos game" driver (:func:`mathkit.fractals_chaos.chaos_game`)
with different affine-map collections.
"""

# %%
from mathkit.fractals_chaos import BarnsleyFern, SierpinskiCarpet, SierpinskiTriangle
from mathkit.fractals_chaos.visualizers.plots import plot_ifs_points

# %%
# Barnsley's fern
# ----------------------

fern_points = BarnsleyFern().generate(40000, seed=0)
plot_ifs_points(fern_points, color="darkgreen")

# %%
# Sierpinski triangle
# ----------------------

triangle_points = SierpinskiTriangle().generate(40000, seed=0)
plot_ifs_points(triangle_points, color="steelblue")

# %%
# Sierpinski carpet
# ----------------------

carpet_points = SierpinskiCarpet().generate(40000, seed=0)
plot_ifs_points(carpet_points, color="firebrick")
