r"""Cyclic and permutation groups, with Cayley table generation and
group-property checks (order, identity, inverses, abelian).

Every construction here is hand-rolled from the textbook definitions --
finite group theory has no ``numpy``/``scipy`` equivalent. See Dummit &
Foote, *Abstract Algebra*, 3rd ed., Ch. 1-4.
"""

from __future__ import annotations

from mathematicskit.abstract_algebra.core.base import FiniteGroup, GroupPropertiesResult

__all__ = ["CyclicGroup", "PermutationGroup", "DihedralGroup", "QuaternionGroup", "group_properties"]


class CyclicGroup(FiniteGroup):
    r"""The cyclic group :math:`\mathbb{Z}_n = \{0, 1, \dots, n-1\}` under addition mod ``n``.

    Generated by a single element (e.g. ``1``); every finite cyclic
    group of order ``n`` is isomorphic to this one. See Dummit & Foote,
    *Abstract Algebra*, 3rd ed., Sec. 1.3, 2.3.

    Parameters
    ----------
    n : int
        Group order, ``n >= 1``.

    Examples
    --------
    >>> g = CyclicGroup(5)
    >>> g.operate(3, 4)
    2
    >>> g.inverse(3)
    2
    >>> g.is_abelian()
    True
    """

    def __init__(self, n: int):
        if n < 1:
            raise ValueError("n must be >= 1")
        self.n = int(n)

    @property
    def elements(self) -> list:
        return list(range(self.n))

    def identity(self) -> int:
        return 0

    def operate(self, a: int, b: int) -> int:
        return (a + b) % self.n

    def inverse(self, a: int) -> int:
        return (-a) % self.n


class PermutationGroup(FiniteGroup):
    r"""The group generated by a set of permutations, under composition.

    Elements are tuples ``p`` with ``p[i]`` = the image of ``i`` under
    the permutation; the full element set is found by closing the
    generators under composition (a breadth-first search from the
    identity). ``generators=None`` builds the full symmetric group
    :math:`S_n` (generated by an adjacent transposition and the full
    n-cycle). See Dummit & Foote, *Abstract Algebra*, 3rd ed., Sec. 1.3,
    1.6.

    Parameters
    ----------
    degree : int
        The permutations act on ``{0, ..., degree - 1}``.
    generators : list of tuple, optional
        Generating permutations; defaults to generators of the full
        symmetric group :math:`S_{\text{degree}}`.

    Examples
    --------
    >>> # S_3, the symmetric group on 3 elements: order 6, non-abelian.
    >>> g = PermutationGroup(3)
    >>> g.order
    6
    >>> g.is_abelian()
    False
    >>> # A cyclic subgroup: generated by the 3-cycle (0 1 2).
    >>> g3 = PermutationGroup(3, generators=[(1, 2, 0)])
    >>> g3.order
    3
    """

    def __init__(self, degree: int, generators=None):
        self.degree = int(degree)
        if generators is None:
            if self.degree < 2:
                generators = [tuple(range(self.degree))]
            else:
                transposition = list(range(self.degree))
                transposition[0], transposition[1] = transposition[1], transposition[0]
                cycle = list(range(1, self.degree)) + [0]
                generators = [tuple(transposition), tuple(cycle)]
        self.generators = [tuple(g) for g in generators]
        self._elements = self._generate_closure()

    def _compose(self, p, q) -> tuple:
        """(p . q)(i) = p(q(i)): apply q first, then p."""
        return tuple(p[q[i]] for i in range(self.degree))

    def _generate_closure(self) -> list:
        identity = tuple(range(self.degree))
        elements = {identity}
        frontier = [identity]
        while frontier:
            new_frontier = []
            for elem in frontier:
                for g in self.generators:
                    composed = self._compose(elem, g)
                    if composed not in elements:
                        elements.add(composed)
                        new_frontier.append(composed)
            frontier = new_frontier
        return sorted(elements)

    @property
    def elements(self) -> list:
        return self._elements

    def identity(self) -> tuple:
        return tuple(range(self.degree))

    def operate(self, a: tuple, b: tuple) -> tuple:
        return self._compose(a, b)

    def inverse(self, a: tuple) -> tuple:
        inv = [0] * self.degree
        for i, v in enumerate(a):
            inv[v] = i
        return tuple(inv)


class DihedralGroup(PermutationGroup):
    r"""The dihedral group :math:`D_n` of symmetries of a regular ``n``-gon, of order :math:`2n`.

    Realized as permutations of the polygon's vertices ``0, ..., n-1``,
    generated by the rotation :math:`r: i \mapsto i+1 \pmod n` and the
    reflection :math:`s: i \mapsto -i \pmod n`. Felix Klein's 1872
    Erlangen program made groups like this -- the transformations that
    preserve a figure -- the organizing principle of geometry. See
    Dummit & Foote, *Abstract Algebra*, 3rd ed., Sec. 1.2.

    Parameters
    ----------
    n : int
        Number of polygon vertices, ``n >= 3``.

    Examples
    --------
    >>> d4 = DihedralGroup(4)  # symmetries of a square
    >>> d4.order
    8
    >>> d4.is_abelian()
    False
    """

    def __init__(self, n: int):
        if n < 3:
            raise ValueError("n must be >= 3")
        self.n = int(n)
        rotation = tuple((i + 1) % n for i in range(n))
        reflection = tuple((-i) % n for i in range(n))
        super().__init__(n, generators=[rotation, reflection])

    @property
    def rotation(self) -> tuple:
        """tuple: The generating rotation by one vertex."""
        return self.generators[0]

    @property
    def reflection(self) -> tuple:
        """tuple: The generating reflection through vertex 0."""
        return self.generators[1]


_QUATERNION_UNIT_PRODUCTS = {
    ("1", "1"): (1, "1"),
    ("1", "i"): (1, "i"),
    ("1", "j"): (1, "j"),
    ("1", "k"): (1, "k"),
    ("i", "1"): (1, "i"),
    ("j", "1"): (1, "j"),
    ("k", "1"): (1, "k"),
    ("i", "i"): (-1, "1"),
    ("j", "j"): (-1, "1"),
    ("k", "k"): (-1, "1"),
    ("i", "j"): (1, "k"),
    ("j", "k"): (1, "i"),
    ("k", "i"): (1, "j"),
    ("j", "i"): (-1, "k"),
    ("k", "j"): (-1, "i"),
    ("i", "k"): (-1, "j"),
}


class QuaternionGroup(FiniteGroup):
    r"""The quaternion group :math:`Q_8 = \{\pm1, \pm i, \pm j, \pm k\}` under quaternion multiplication.

    Elements are the strings ``"1", "-1", "i", "-i", "j", "-j", "k", "-k"``,
    multiplied by William Rowan Hamilton's 1843 rules
    :math:`i^2 = j^2 = k^2 = ijk = -1`. It is the smallest non-abelian
    group in which every subgroup is normal. See Dummit & Foote,
    *Abstract Algebra*, 3rd ed., Sec. 1.5.

    Examples
    --------
    >>> q = QuaternionGroup()
    >>> q.operate("i", "j"), q.operate("j", "i")
    ('k', '-k')
    >>> q.operate(q.operate("i", "j"), "k")  # ijk = -1
    '-1'
    >>> q.element_order("i")
    4
    """

    _ELEMENTS = ["1", "-1", "i", "-i", "j", "-j", "k", "-k"]

    @property
    def elements(self) -> list:
        return list(self._ELEMENTS)

    def identity(self) -> str:
        return "1"

    @staticmethod
    def _split(a: str) -> tuple:
        return (-1, a[1:]) if a.startswith("-") else (1, a)

    def operate(self, a: str, b: str) -> str:
        sa, ua = self._split(a)
        sb, ub = self._split(b)
        s, u = _QUATERNION_UNIT_PRODUCTS[(ua, ub)]
        return u if sa * sb * s == 1 else "-" + u

    def inverse(self, a: str) -> str:
        sign, unit = self._split(a)
        if unit == "1":
            return a
        return unit if sign == -1 else "-" + unit


def group_properties(group: FiniteGroup) -> GroupPropertiesResult:
    """Summarize a finite group's order, abelian-ness, and every element's order.

    Parameters
    ----------
    group : FiniteGroup

    Returns
    -------
    GroupPropertiesResult

    Examples
    --------
    >>> result = group_properties(CyclicGroup(4))
    >>> result.order
    4
    >>> result.is_abelian
    True
    >>> result.element_orders
    {0: 1, 1: 4, 2: 2, 3: 4}
    """
    orders = {e: group.element_order(e) for e in group.elements}
    return GroupPropertiesResult(order=group.order, is_abelian=group.is_abelian(), identity=group.identity(), element_orders=orders)
