r"""Subgroup and coset enumeration for small finite groups.

No numpy/scipy equivalent. See Dummit & Foote, *Abstract Algebra*, 3rd
ed., Sec. 2.1 (subgroups), 3.1 (cosets), and Lagrange's theorem (Sec. 3.2).
"""

from __future__ import annotations

from mathematicskit.abstract_algebra.core.base import FiniteGroup

__all__ = ["cyclic_subgroup", "all_subgroups", "left_cosets"]


def cyclic_subgroup(group: FiniteGroup, generator) -> list:
    r"""The cyclic subgroup :math:`\langle g \rangle = \{e, g, g^2, \dots\}` generated by a single element.

    Its size equals :meth:`~mathematicskit.abstract_algebra.core.base.FiniteGroup.element_order`\
    (`generator`) -- by Lagrange's theorem, this always divides
    :math:`|G|`. See Dummit & Foote, *Abstract Algebra*, 3rd ed.,
    Sec. 2.3.

    Parameters
    ----------
    group : FiniteGroup
    generator

    Returns
    -------
    list

    Examples
    --------
    >>> from mathematicskit.abstract_algebra.systems.groups import CyclicGroup
    >>> cyclic_subgroup(CyclicGroup(6), 2)
    [0, 2, 4]
    """
    e = group.identity()
    elements = [e]
    x = generator
    while x != e:
        elements.append(x)
        x = group.operate(x, generator)
    return elements


def all_subgroups(group: FiniteGroup) -> list:
    r"""Every subgroup of a small finite group, found by closing every subset of generators.

    Builds the subgroup generated by each subset of :attr:`group.elements
    <mathematicskit.abstract_algebra.core.base.FiniteGroup.elements>` (closing
    under the group operation and inverses) and deduplicates -- feasible
    only for small groups (this is exponential in :math:`|G|`), but
    exact. See Dummit & Foote, *Abstract Algebra*, 3rd ed., Sec. 2.1.

    Parameters
    ----------
    group : FiniteGroup

    Returns
    -------
    list of list
        Every distinct subgroup, each as a sorted-by-first-appearance
        list of elements, including the trivial subgroup ``{e}`` and
        ``group.elements`` itself.

    Examples
    --------
    >>> from mathematicskit.abstract_algebra.systems.groups import CyclicGroup
    >>> subgroups = all_subgroups(CyclicGroup(6))
    >>> sorted(len(s) for s in subgroups)  # divisors of 6: 1, 2, 3, 6
    [1, 2, 3, 6]
    """
    e = group.identity()
    found = {frozenset([e]): [e]}

    def _closure(gens):
        elements = {e}
        frontier = [e]
        gens_and_inverses = list(gens) + [group.inverse(g) for g in gens]
        while frontier:
            new_frontier = []
            for elem in frontier:
                for g in gens_and_inverses:
                    composed = group.operate(elem, g)
                    if composed not in elements:
                        elements.add(composed)
                        new_frontier.append(composed)
            frontier = new_frontier
        return elements

    for g in group.elements:
        elements = _closure([g])
        key = frozenset(elements)
        if key not in found:
            found[key] = list(elements)

    # Also close pairs of generators, to find non-cyclic subgroups.
    elems = group.elements
    for i, a in enumerate(elems):
        for b in elems[i + 1 :]:
            elements = _closure([a, b])
            key = frozenset(elements)
            if key not in found:
                found[key] = list(elements)

    return list(found.values())


def left_cosets(group: FiniteGroup, subgroup: list) -> list:
    r"""The left cosets :math:`gH` of `subgroup` in `group`.

    Partitions :attr:`group.elements
    <mathematicskit.abstract_algebra.core.base.FiniteGroup.elements>` into
    ``|G|/|H|`` disjoint cosets (Lagrange's theorem). See Dummit &
    Foote, *Abstract Algebra*, 3rd ed., Sec. 3.1-3.2.

    Parameters
    ----------
    group : FiniteGroup
    subgroup : list
        A subgroup of `group` (e.g. from :func:`cyclic_subgroup` or
        :func:`all_subgroups`).

    Returns
    -------
    list of list

    Examples
    --------
    >>> from mathematicskit.abstract_algebra.systems.groups import CyclicGroup
    >>> g = CyclicGroup(6)
    >>> h = cyclic_subgroup(g, 3)  # H = {0, 3}
    >>> left_cosets(g, h)
    [[0, 3], [1, 4], [2, 5]]
    """
    remaining = set(group.elements)
    cosets = []
    for g in group.elements:
        if g not in remaining:
            continue
        coset = [group.operate(g, h) for h in subgroup]
        cosets.append(coset)
        remaining -= set(coset)
    return cosets
